### PR TITLE
support pure json output

### LINKED ISSUE #24: [FR] support pure json output
Motivation: when we only want to parse the raw token, and then query its contents using `jq` utility.
For instance, extracting `iat` element from the payload part.

### PR DESCRIPTION
**Pull request by kleinron**
resolve https://github.com/troyharvey/jwt-cli/issues/24

### CODE REVIEW

**Review by troyharvey — CHANGES_REQUESTED** [review]
Thanks for the PR! I love the idea of json output. I subscribe to the Larry Tesler school of thought that we should avoid "modes" if possible. Could we change the flag to just be `--output=json` and remove "mode" language?

When the `output` option is absent we output the default "full" formatted output and we can skip having a `--output=full` option because that's the default behavior.

**Comment by kleinron** [comment]
in most command line tools I use, the `--output` flag is used for the output file itself (e.g. where to write the output to).
therefore I wouldn't use this specific flag.
maybe `format` is more suitable?

**Comment by troyharvey** [comment]
Right now I'm using `kubectl` almost as much as I use `git` and they use the `--output` flag. So does `aws`. What tool are you thinking of?

* aws

        aws iam list-users --output json

* kubectl

        kubectl --output json get service django-app

**Comment by kleinron** [comment]
I had `curl` in mind.
Anyways, this seems to be a matter of taste. I'll change according to your decision.

**Comment by kleinron** [comment]
hi, please review 😃

**Comment by troyharvey** [comment]
Thank you! This is great. 🥳

**Pull request merged**
