### PR TITLE
Adding verification functionality

### PR DESCRIPTION
**Pull request by bharkreader**
I really like this tool!

I want to be able to use it to verify jwts too though. I'm proposing the simplest solution, which is adding the secret as an optional second argument. When it is provided, then a green or red string at the bottom will indicate whether the signature is valid. If not provided, the script works as before.

### CODE REVIEW

**Comment by troyharvey** [comment]
This sounds great! Do you mind dropping [a screenshot](https://giphy.com/apps/giphycapture) into the description so I can see what it looks like?

**Comment by bharkreader** [comment]
Screen Shot 2019-10-25 at 1 37 42 PM

**Comment by bharkreader** [comment]
Now with ✻s!
Screen Shot 2019-10-25 at 1 42 22 PM

**Comment by bharkreader** [comment]
fixes #14

**Pull request merged**
